config/routes.rb
resources :goods
match ':project_id/goods'  => "goods#index"
match ':project_id/goods/new'  => "goods#new"
match ':project_id/goods/:id'  => "goods#show"
match ':project_id/goods/:id/edit'  => "goods#edit"

resources :demo
match ':id/demo'  => "demo#index"

app/models/good.rb
class Good < ActiveRecord::Base
    belongs_to :project
    belongs_to :issue

    validates_presence_of :title
    validates_uniqueness_of :title
    validates_numericality_of :price, :quantity, :issue_id
    validates_presence_of :project, :message => :message_goods_should_have_project
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  before_filter :find_project
  def index
  end
  private

  def find_project
    id = params[:id]
    @project = Project.find(id)
  rescue ActiveRecord::RecordNotFound
    render_404
    end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_filter :find_project, :authorize
  before_filter :find_good, :authorize, :except => [:index, :new, :create]

  helper :sort
  include SortHelper
  def index
    sort_init 'created_on', 'desc'
    sort_update %w(title price quantity manufacture created_on)

    scope = Good
    scope = Good.where("title like ?", "%#{params[:title]}%") if params[:title].present?
    @goods = scope.order(sort_clause)
  end

  def new
    @good = Good.new
    @good.project = @project
    @good.attributes = params[:good] if params[:good] && params[:good].is_a?(Hash)
  end

  def create
    @good = Good.new(params[:good])
    @good.project = @project
    if @good.save
      flash[:notice] = l(:notice_successful_create)
      respond_to do |format|
        format.html { redirect_to (params[:continue] ?  {:action => "new", :project_id => @project} : {:action => "show", :project_id => @project, :id => @good} )}
      end
    else
      respond_to do |format|
        format.html { render :action => "new" }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @good.update_attributes(params[:good])
      flash[:notice] = l(:notice_successful_update)
      respond_to do |format|
        format.html { redirect_to :action => "show", :project_id => @project, :id => @good }
      end
    else
      respond_to do |format|
        format.html { render "edit", :project_id => @project, :id => @good  }
      end
    end
  end

  def destroy
    if @good.destroy
      flash[:notice] = l(:notice_successful_delete_good)
    end
    redirect_to :action => 'index', :project_id => @project
  end

  private

  def find_project
    project_id = params[:project_id]
    @project = Project.find(project_id)
  rescue ActiveRecord::RecordNotFound
    render_404
    end

  def find_good
    good_id = params[:id]
    @good = Good.find(good_id)
  rescue ActiveRecord::RecordNotFound
    render_404
    end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_form.html.erb
<%= error_messages_for 'good' %>

<div class="box tabular">
	<!--[form:good]-->
	<p>
		<%= f.text_field :title, :required => true, :size => 60, :label => :field_good_title %>
	</p>
	<p>
		<%= f.text_field :price, :required => false, :size => 10, :label => :field_good_price %>
	</p>
	<p>
		<%= f.text_field :quantity, :required => false, :size => 10, :label => :field_good_quantity %>
	</p>
	<p>
		<%= f.text_field :manufacture, :required => false, :size => 20, :label => :field_good_manufacture %><%= calendar_for('good_manufacture') %>
	</p>
	<p>
		<%= f.text_field :issue_id, :required => false, :size => 10, :label => :field_good_issue_id %>
	</p>
</div>

app/views/goods/edit.html.erb
<h2><%= @good.title%></h2>
<%= labelled_form_for @good, :url => {:action => 'update', :id => @good, :project_id => @project} do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_submit) %>
<% end %>

app/views/goods/index.html.erb
<div class="contextual">
	<% if User.current.allowed_to?(:add_goods, @project) %>
	<%= link_to l(:label_good_new), {:controller => 'goods', :action => 'new', :project_id => @project}, :class => 'icon icon-add' %>
	<% end %>
</div>

<h2><%= l(:label_goods)%></h2>

<fieldset>
	<legend>
		<%= l(:label_filter_plural) %>
	</legend>
	<%= form_tag({:controller => 'goods', :action => 'index', :project_id => @project}, :method => :get) do %>
	<label for='title'><%= l(:field_good_title) %>:</label>
	<%= text_field_tag 'title', params[:title], :size => 30 %>
	<%= submit_tag l(:button_apply), :class => "small", :name => nil %>
	<%= link_to l(:button_clear), {:controller => 'goods', :action => 'index', :project_id => @project}, :class => 'icon icon-reload' %>
</fieldset>
<% end %>
&nbsp;

<div class="autoscroll">
	<table class="list">
		<thead>
			<tr>
				<%= sort_header_tag('title', :caption => l(:field_good_title)) %>
				<%= sort_header_tag('price', :caption => l(:field_good_price)) %>
				<%= sort_header_tag('quantity', :caption => l(:field_good_quantity)) %>
				<%= sort_header_tag('manufacture', :caption => l(:field_good_manufacture)) %>
				<%= sort_header_tag('created_on', :caption => l(:field_created_on), :default_order => 'desc') %>
			</tr>
		</thead>
		<tbody>
			<% for good in @goods -%>
			<td class="title"><%= link_to h(good.title), {:controller => 'goods', :action => 'show', :id => good, :project_id => @project} %></td>
			<td class="price"><%= number_to_currency(good.price, :precision => 2) %></td>
			<td class="quantity"><%= h(good.quantity) %></td>
			<td class="manufacture"><%= format_time(good.manufacture) %></td>
			<td class="created_on"><%= format_time(good.created_on) %></td>
			</tr>
			<% end -%>
		</tbody>
	</table>
</div>

app/views/goods/new.html.erb
<%= title l(:label_good_new) %>
<%= labelled_form_for @good, :url => {:action => 'create', :project_id => @project} do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_create) %>
<%= submit_tag l(:button_create_and_continue), :name => 'continue' %>
<% end %>

app/views/goods/show.html.erb
<div class="contextual">
	<%= link_to l(:button_edit), {:controller => 'goods', :action => 'edit', :id => @good, :project_id => @project}, :class => 'icon icon-edit' if User.current.allowed_to?(:edit_goods, @project) %>
	<%= link_to l(:button_delete), good_path(@good, :project_id => @project), :method => :delete, :class => 'icon icon-del' if User.current.allowed_to?(:delete_goods, @project) %>
</div>

<h2><%= @good.title%></h2>

<div class="splitcontentleft">
	<fieldset class="box tabular">
		<% if @good.price %>
		<p>
			<label><%= l(:field_good_price)%> :</label> <%= number_to_currency( @good.price, :precision => 2) %>
		</p>
		<% end %>
		<p>
			<label><%= l(:field_good_quantity)%> :</label> <%= @good.quantity %>
		</p>
		<% if @good.manufacture %>
		<p>
			<label><%= l(:field_good_manufacture)%> :</label> <%= format_time(@good.manufacture)%>
		</p>
		<% end %>
		<% if @good.issue_id %>
		<p>
			<label><%= l(:field_good_issue_id)%> :</label> <%= link_to @good.issue_id, {:controller => 'issues', :action => 'show', :id => @good.issue_id} %>
		</p>
		<% end %>
	</fieldset>
</div>

app/views/issues/_show_good.html.erb
<% if User.current.allowed_to?(:view_goods, @project) %>
    <% good = Good.find_by_issue_id(issue) %>
    <% if good %>
        <th><%=l(:field_good)%> :</th><td><%= link_to h(good.title), {:controller => 'goods', :action => 'show', :id => good, :project_id => @project} %></td>
    <% end %>
<% end %>